import os
import sys


_ROOT = os.path.dirname(os.path.abspath(__file__))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from WNG import toolbox as _toolbox  # noqa: E402


def _export_tool_classes(tool_classes):
    """Expose toolbox classes from this Python toolbox module.

    Args:
        tool_classes: Tool class objects generated by the support package.

    Returns:
        A list of module-local tool class objects for ArcGIS discovery.
    """
    exported = []
    for tool_class in tool_classes:
        local_class = type(
            tool_class.__name__,
            (tool_class,),
            {
                "__doc__": getattr(tool_class, "__doc__", None),
                "__module__": __name__,
            },
        )
        globals()[local_class.__name__] = local_class
        exported.append(local_class)
    return exported


_TOOLS = _export_tool_classes(_toolbox._build_tools())


class Toolbox(object):
    """ArcGIS Python toolbox entry point."""

    def __init__(self):
        """Initialize toolbox metadata and generated tool classes."""
        self.label = "Whitebox Next Gen Toolbox"
        self.alias = "WNG"
        self.tools = _TOOLS
